CREATE TABLE `mastercustomer` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `kode_customer` VARCHAR(20) NOT NULL UNIQUE,
  `nama_customer` VARCHAR(100) NOT NULL,
  `alamat` VARCHAR(255) DEFAULT NULL,
  `contact_person` VARCHAR(100) DEFAULT NULL,
  `kota` VARCHAR(100) DEFAULT NULL,
  `provinsi` VARCHAR(100) DEFAULT NULL,
  `sales` VARCHAR(100) DEFAULT NULL,
  `no_hp` VARCHAR(30) DEFAULT NULL,
  `batas_piutang` DECIMAL(18,2) DEFAULT 0,
  `npwp_nomor` VARCHAR(50) DEFAULT NULL,
  `npwp_atas_nama` VARCHAR(100) DEFAULT NULL,
  `npwp_alamat` VARCHAR(255) DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
